steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone','--single-branch','--branch','${_GIT_SOURCE_BRANCH}','${_GIT_SOURCE_URL}']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds','submit','--tag','gcr.io/$PROJECT_ID/gcp-data-drive']
  dir: 'DIY-Tools/gcp-data-drive'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run','deploy','gcp-data-drive','--image','gcr.io/$PROJECT_ID/gcp-data-drive','--platform','managed','--region','us-central1','--allow-unauthenticated']
  dir: 'DIY-Tools/gcp-data-drive'
